### PR TITLE
Add a test case for adding a new record via a fork

### PR DESCRIPTION
**Pull request by chbonser**
See issue https://github.com/orbitjs/ember-orbit/issues/299.

Confusingly this tests passes, but the same workflow fails in my app.

### CODE REVIEW

**Comment by chbonser** [comment]
I'm realizing now that the test flow here does work in my app BUT what doesn't work right is syncing with my remote source. Let me see if I can setup a test for that...

**Comment by tchak** [comment]
If there is an issue around a flow where you add a record to a fork and then merge it back to the main store and expect it to be saved to the remote store it would probably be an issue in orbit itself and not ember-orbit. I recommend try to replicate the flow in a test in [@orbit/integration-tests](https://github.com/orbitjs/orbit/tree/master/packages/%40orbit/integration-tests)

**Comment by chbonser** [comment]
Thanks @tchak. You are correct. Please see the failing test here https://github.com/orbitjs/orbit/pull/777

**Comment by dgeb** [comment]
Fixed as noted here: https://github.com/orbitjs/ember-orbit/issues/299#issuecomment-692317011

**Pull request closed without merging**
