### PR TITLE
Upgrade ember, orbit.js and other dependencies

### PR DESCRIPTION
**Pull request by tchak**

### CODE REVIEW

**Comment by tchak** [comment]
ember-cli-test-loader dropped node 8 support: https://github.com/ember-cli/ember-cli-test-loader/commit/423cdd03fde93d4ece47c0167ca52a2bb4c0e930

Should we do the same @dgeb? node 8 will be dead in January https://nodejs.org/en/about/releases/

cc @Turbo87

**Comment by Turbo87** [comment]
@tchak you don't need the `ember-cli-test-loader` dependency at all. it is already brought in by `ember-qunit`

**Comment by devotox** [comment]
This looks like it should fix the linting errors

**Comment by tchak** [comment]
Thanks @Turbo87, I removed explicit `ember-cli-test-loader` dependency and it works now 🎉

**Pull request merged**
