### PR TITLE
Properly handle single results in LiveQuery

### LINKED ISSUE #178: `liveQuery` fails with a query that has a singular result (like `findRecord`)
Attempting to `liveQuery` a single record will fail

For example:

```  
model({ schedule_id }) {
    return this.store.liveQuery(q => {
      return q.findRecord({ type: 'schedule', id: schedule_id })
    });
  },
```

### PR DESCRIPTION
**Pull request by tchak**
fix #178

### CODE REVIEW

**Comment by tchak** [comment]
A liveQuery with `findRecord` though is not really workable, as it will throw in case it can not find a record. Should we rescue errors in LiveQueries?

**Comment by tchak** [comment]
For a bit more context: the current code in `live-query.js` `content` computed property is not working properly anyway. It expect a query to return an object with result members witch is not a thing in orbit (maybe used to be a find in older versions?).

**Comment by dgeb** [comment]
I am just really torn about this approach, because it means changing the shape of the result.

I'm still processing what I consider the "right" answer to be here ...

**Comment by tchak** [comment]
I listed different options I see in #178 and I am quite firmly convinced that the normalize to array is the less worse one :)

**Comment by tchak** [comment]
I will close this. In #241 I am proposing a new liveQuery interface which will be more selective about where to enable live updates on single record queries.

**Pull request closed without merging**
