### PR TITLE
Allow ember-orbit to be used in addons

### PR DESCRIPTION
**Pull request by devotox**

### CODE REVIEW

**Comment by tchak** [comment]
Thank you for this PR!

I think you need to run `yarn lint:js --fix` to fix lint error

**Comment by tchak** [comment]
Hmm, I just tried it my self and something is not right with the linter. I will investigate.

**Comment by tchak** [comment]
The listing error should be fixed on master.

@dgeb could you have a look at this? You know more then I do about addons :)

**Comment by dgeb** [comment]
@devotox thanks for this PR! It resolves an issue that @lukemelia reported.

I amended one of the commits to fix some minor formatting issues. I'll get a new patch release out shortly.

**Pull request merged**
