### PR TITLE
Add ember-cli-addon-docs site

### PR DESCRIPTION
**Pull request by rwwagner90**
Screen Shot 2020-01-23 at 8 49 15 AM

This adds ember-cli-addon-docs and a new app using it to `/docs`. It's using the yuidoc parser, so we should be able to document things with yuidoc and have them automatically be added to the docs too.

I added a few yuidoc comments to show how we would document methods so they would be auto added to the API reference.

### CODE REVIEW

**Comment by dgeb** [comment]
@rwwagner90 thanks for getting this started! This looks great 😍 

Do you know if anyone has integrated ts docs together with ember-cli-addon-docs? This would keep the inline docs more minimal and based on the typings.

**Comment by rwwagner90** [comment]
@dgeb you're welcome!

People have tried to do TSDoc I think, but I don't think it works and would need a custom parser like ember-cli-addon-docs-yuidoc, but written for TSDoc.

**Comment by tchak** [comment]
Thanks – this is great! I have concerns about shipping `ember-cli-addon-docs` as part of the addon – even if it is just a development dependency a lot of people reported having conflicts because of this addon. I was thinking, could we keep the `ember-cli-addon-docs` on a separate branch and build the documentation website from there?

**Comment by rwwagner90** [comment]
> a lot of people reported having conflicts because of this addon

@tchak can you elaborate? I'm using it in most of my addons with no issues.

**Comment by tchak** [comment]
Maybe it was mostly resolved. But main issue was if I remember correctly is the fact that `ember-cli-addon-docs` ships with `ember-data` and other addons and they end up polluting development environment. I remember @turbo87 mentioning he had issues. Could you shim-in here @turbo87? Is it safe to just include `ember-cli-addon-docs` on the main branch?

**Comment by rwwagner90** [comment]
@tchak my thoughts are since ember-orbit is an addon, and ember-cli-addon-docs is just a devDep, it's never going to end up polluting apps, since it shouldn't be shipped to the consuming apps. It's also setup as a separate app here, and all the deps are in its own folder, so I think we're safe.

**Comment by tchak** [comment]
I just realised that it is setup in a separate folder and there is nothing about `ember-cli-addon-docs` in the main `package.json`. Awesome! Sorry I should have reviewed better before posting :)

**Comment by rwwagner90** [comment]
> I just realised that it is setup in a separate folder and there is nothing about ember-cli-addon-docs in the main package.json. Awesome! Sorry I should have reviewed better before posting :)

No worries! Any other concerns? Would love to get this in so we can start releasing some docs and I have several other pages I want to work on from my experiences getting ember-orbit up and running.

**Comment by dgeb** [comment]
Looks like a great start, @rwwagner90. Let's get this merged, iterate a bit, and then publish.

Thanks again!

**Pull request merged**
