### PR TITLE
Use glimmer cache API

### PR DESCRIPTION
**Pull request by tchak**
This PR replace hacks with public API implementation.

One problem surfaced. In EO we have two levels of cache. In my opinion, more by accident than by design. We use `@orbit/memory` source as cache, but we also cache on the model because of how computed properties used to work. This is why something like this works.

```ts
record.name = "Paul"
record.name // "Paul"
```

Behind the scenes it calls `store.update(t => t.replaceAttribute())` which is async. So if `record.name` delegates to memory source, the value will be updated only on next tick.

The proposed solution is to use `source.cache.patch(t => t.replaceAttribute())` which will synchronously update memory source.

We can, of course, implement a model level caching with the new API, but I think this might be a good opportunity to fix what I think is an inconsistency.

### CODE REVIEW

**Comment by tchak** [comment]
I changed this PR to use a secondary on model cache. It is reset in case of a failure.

**Comment by tchak** [comment]
One last remark on this.

```ts
card.enabled = true;
const enabledCards = store.liveQuery(q => q.findRecord('card').filter({ attribute: 'enabled', value: true }));
enabledCards.includes(card) // => false
```
This is already the case with current implementation. The only way I see to fix this is using `cache.patch`...

**Comment by dgeb** [comment]
Sorry, I created some merge conflicts merging some of your earlier PRs. I'll investigate soon.

**Comment by tchak** [comment]
I fixed conflicts. But master is broken with beta/canary. I am investigating. It have to do with destroyable api.

**Comment by tchak** [comment]
I fixed test on master

**Comment by dgeb** [comment]
@tchak thanks for the fixes! Reviewing this again now ...

**Pull request merged**
